dist: xenial
language: ruby
cache: bundler
before_install:
- bundle -v
- rm -f Gemfile.lock
- gem update --system $RUBYGEMS_VERSION
- gem --version
- bundle -v
script:
- bundle exec rake $CHECK
bundler_args: "--without system_tests"
rvm:
- 2.5.3
stages:
- static
- spec
- acceptance
- if: tag =~ ^v\d
  name: deploy
matrix:
  fast_finish: true
  include:
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=deb_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then bundle exec rake 'litmus:install_agent[puppet5-nightly]';
      else  bundle exec rake 'litmus:install_agent[puppet5]'; fi
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORM=deb_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then bundle exec rake 'litmus:install_agent[puppet6-nightly]';
      else  bundle exec rake 'litmus:install_agent[puppet6]'; fi
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el7_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el7]'
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then bundle exec rake 'litmus:install_agent[puppet5-nightly]';
      else  bundle exec rake 'litmus:install_agent[puppet5]'; fi
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORM=el7_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el7]'
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then bundle exec rake 'litmus:install_agent[puppet6-nightly]';
      else  bundle exec rake 'litmus:install_agent[puppet6]'; fi
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el6_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el6]'
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then bundle exec rake 'litmus:install_agent[puppet5-nightly]';
      else  bundle exec rake 'litmus:install_agent[puppet5]'; fi
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el6_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el6]'
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then bundle exec rake 'litmus:install_agent[puppet6-nightly]';
      else  bundle exec rake 'litmus:install_agent[puppet6]'; fi
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file
      rubocop syntax lint metadata_lint"
    stage: static
  - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
    rvm: 2.4.5
    stage: spec
  - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
    rvm: 2.5.3
    stage: spec
branches:
  only:
  - master
  - "/^v\\d/"
  - release
  - "/^travis.+/"
notifications:
  email: false
  slack:
    secure: Udaslw8I192EJnJ4EDJJh2OocUekDJHkYSMIF5+G9FO2SM5Xd6Er4u8M+mIbd7ic9vt7KAEBSBou9IatDS87JPaW2BD8+Agxxhs6cYUgnqwYl0NdkbGQBzV9VU2JIiOS6SCI69wDwdOOzw5CWrBB10m3OIkH4dj3mZ3SYxWyXjqj8h/PyAUk6RJhBEx0qtXkOJr82FHdSjM1/btLfYDhcuXpPE7Xf2p3G+U8SScKndPPUdFewEytFVkGfkqfjEtBF8uP7x9HrX+0KwgEt79aSjAFzLCGWxdZETG6l1gFXE45lfY5q0Xh4VeqUGBid8zU5KWHZpJKxazrPP/cTSWcAM4qSQXs7iCPVix9LPu63dGo4ldfRrBn2FmIU6MG5YCG7GKOckBXoBMLoo1bsmbFltmS2I4bHMy/LDeQwnLcM+wY+Q3IONuHMcF2dZxRRe/fLIlR+tChUP8Yywuf4XABhtbS75yO1ainW4d3untUwDjpl4+XCc/L0aZHAhMtXKcNWkSrkVHBRIljSdYf5APlyERjjE1+N4wOTOvWR6ZmlwOUqerP7OCw6s7nv9JBzdeFhczJ75EeSxF279jmSzU3U7uqejNSfvjpNo3z/cn4CtWyZ0wL4cl1huQo1tZql6rVWD2d5ZBj5ttMA+/rNt2DdKaz7DI1Q0lKkAuDZSYGFwk=
